[package]
name = "rusttp"
version = "0.1.0"
edition = "2021"
authors = ["Aryan Ahmed", "thearyanahmed <thearyanahmed@gmail.com>"]

[dependencies]
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "net",
    "io-util",
] }
